name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering of the workflow
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
    
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Ensure submodules are checked out

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}

      - name: Build project
        run: python3 Buildall.py vs2022 vc143 x64 MinSizeRel

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: |
            Build/vs2022-win-vc143-x64/Bin/MinSizeRel/dxcompiler.dll
            Build/vs2022-win-vc143-x64/Bin/MinSizeRel/ShaderConductor.dll
            Build/vs2022-win-vc143-x64/Bin/MinSizeRel/ShaderConductorWrapper.dll
  
  linux-x64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Ensure submodules are checked out

      - name: Build project
        run: python3 BuildAll.py ninja clang x64 MinSizeRel

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: |
            Build/ninja-linux-clang-x64-Release/Lib/libdxcompiler.so
            Build/ninja-linux-clang-x64-Release/Lib/libShaderConductor.so
            Build/ninja-linux-clang-x64-Release/Lib/libShaderConductorWrapper.so
  
  linux-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Ensure submodules are checked out

      - name: Build project
        run: python3 BuildAll.py ninja clang arm64 MinSizeRel

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: |
            Build/ninja-linux-clang-arm64-Release/Lib/libdxcompiler.so
            Build/ninja-linux-clang-arm64-Release/Lib/libShaderConductor.so
            Build/ninja-linux-clang-arm64-Release/Lib/libShaderConductorWrapper.so

  macos-arm64:
    runs-on: macos-15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Ensure submodules are checked out
      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}

      - name: Build project
        run: python BuildAll.py ninja clang arm64 MinSizeRel 

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-arm64
          path: |
            Build/ninja-osx-clang-arm64-MinSizeRel/Lib/libdxcompiler.dylib
            Build/ninja-osx-clang-arm64-MinSizeRel/Lib/libShaderConductor.dylib
            Build/ninja-osx-clang-arm64-MinSizeRel/Lib/libShaderConductorWrapper.dylib